// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://borvxercmcoylcmpcbyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvcnZ4ZXJjbWNveWxjbXBjYnloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3Nzk5OTgsImV4cCI6MjA2MTM1NTk5OH0.urRJDm1S2XDTrjK3obuyj4Rk8Ftj9AOB1Vf_SJM-RD8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);